### ISSUE TITLE
Recruitment QAQC - flag for UP submitted but not yet verified within 60 days

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/qaqc_testing#2]
Please add the following rule to the Recruitment QAQC report:

qc_test: unsure, didn't seem to fit in any of the examples

Label: Flag for UP submitted but not yet verified within 60 days

Description: If UP submitted (699625233)=yes (353358909) and Verification status (821247024) = not yet verified (875007964), flag if today's date is >60 days more than time submitted UP date (430551721) Essentially, flag records that do not have their verification status changed from the default response 'not yet verified' within 60 days of submitting UP.

Logic: for analytics team to translate

Happy to discuss if you have questions!

**Comment by jacobmpeters** [comment]
Hi @robertsamm and @mnataraj92,

I am just now seeing that you are now using our issues page. Apologies for the delay!

I will adjust my notifications to make sure that I see these in the future. 

I'll take a look now.

**Comment by robertsamm** [comment]
Thanks @jacobmpeters let me know if you have any questions about this request! It was my first time putting in an issue for the qc checks and I wasn't sure the exact parameters to put for this one.

**Comment by jacobmpeters** [comment]
@robertsamm Your request is actually very clear and useful! Thank you for putting that effort into it and for following our guidelines.

It turns out that we do not have an existing qc_test for this request. I will look into how difficult would be to add one to our generic qc code. If it is reasonably straightforward to add, I will add it. If it isn't, we may need to ask Jing or Kelsey to add it as a one-off check in one of their weekly reports.

**Comment by jacobmpeters** [comment]
We're discussing this request at our Analytics Team meeting. Looping @jeannewu and @KELSEYDOWLING7 in for our discussion.

**Comment by jacobmpeters** [comment]
@robertsamm We decided to implement this as a separate mini-report that we will since it cannot easily be integrated with our generic QAQC process which we hope to keep more simple so that it can easily be reused. @jeannewu is working on this now.

**Comment by robertsamm** [comment]
Thanks @jacobmpeters! Michelle suggested that this separate mini-report contain all the QAQC checks that can't be incorporated into the regular report so that they aren't in multiple files and that @mnataraj92 reviews this mini-report as part of her regular review.

**Comment by jacobmpeters** [comment]
Sounds good, @robertsamm! @jeannewu is working on coding the rule and I will run it with our regular QAQC process and share it as one file for @mnataraj92 to review. We can iterate on this as needed..

**Comment by jacobmpeters** [comment]
@jeannewu ran this rule for us this week and flagged some participants: https://nih.box.com/s/wo6fzoolfsrtphp3v0yagl6w6xb34b67. @mnataraj92 please take a look and let us know if it is useful. 

Moving forward, I will run Jing's script and include this mini-report in the same folder as the main Recruitment QC Report.

**Comment by mnataraj92** [comment]
the report looks great!

**Comment by robertsamm** [comment]
Thanks @jacobmpeters Michelle and I agree, this report looks great! @mnataraj92 will add the flagged participants in a github issue for KPNW and KPCO to their respective github repository.
