### ISSUE TITLE
Module 4 QC: Using Module 1 variable

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/qaqc_testing#78]
A group of rules about commuting to school in mod4 looks at the response variable to SCHOOL (D_784967158) in Module 1. Is there a way to link these when we run this QC file?

If it's any help, these are the select variables affected:
- D_449752653
- D_959371875
- D_224209278_D_744987950
- D_224209278_D_770959058
- D_659744749
- D_404863614_D_404863614_D_782113721
- D_404863614_D_404863614_D_207263450
- D_404863614_D_404863614_D_638833327
- D_404863614_D_404863614_D_736981982
- D_404863614_D_404863614_D_932195315
- D_404863614_D_404863614_D_279026426
- D_404863614_D_404863614_D_691579493
- D_404863614_D_404863614_D_211269389
- D_940631293
- D_496801729
- D_230528407
- D_345355061_D_467242967
- D_345355061_D_645051966
- D_345355061_D_756061540
- D_345355061_D_198883577
- D_345355061_D_634680635
- D_345355061_D_790657437
- D_345355061_D_107428524
- D_345355061_D_804918983
- D_849811593

**Comment by jacobmpeters** [comment]
Hi Kelsey, 

Yes, we can merge these prior to running the QC. I'll find some time to work on this this week! Thanks for making an Issue.

**Comment by jacobmpeters** [comment]
Commit f0bd14bddc5ae2d95c0fb52b57329a8658b9b14b should resolve this issue.

I'll test it and share the report via Box..

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Great thanks! Just let me know once its ready to review in Box and I'll take a look

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 I can't recall.. Did I share the Module 4 report with you after making this fix?

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Hi, no net yet

**Comment by jacobmpeters** [comment]
Ok! Here it is: https://nih.app.box.com/file/1345214126031

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters Awesome, the only errors left are things IMS needs to fix. Thanks again!
